---

# Create temporary directory
- name: SAP SWPM Pre Install - Create temporary directory
  tempfile:
    state: directory
    suffix: swpmconfig
  register: sap_swpm_tmpdir

# Copy password file to the same location as inifile.params
- name: SAP SWPM Pre Install - Copy password file to the same location as inifile.params
  copy:
    src: "{{ sap_swpm_password_file_path }}/instkey.pkey"
    dest: "{{ sap_swpm_tmpdir.path }}/instkey.pkey"
    remote_src: yes
  when: sap_swpm_use_password_file == "y"

# Run SWPM inifile generation based on ansible role mode
- include_tasks: "swpm_inifile_generate_{{ sap_swpm_ansible_role_mode }}.yml"

# Set fact for SWPM path
- name: SAP SWPM Pre Install - Set fact for SWPM path
  set_fact:
    sap_swpm_sapinst_path: "{{ sap_swpm_sapcar_path }}"

# Extract SWPM
- name: SAP SWPM Pre Install - Extract SWPM
  command: >-
    {{ sap_swpm_sapcar_path }}/{{ sap_swpm_sapcar_file_name }} \
    -xvf {{ sap_swpm_swpm_path }}/{{ sap_swpm_swpm_sar_file_name }} \
    -manifest SIGNATURE.SMF
  register: sap_swpm_extractswpm
  args:
    # chdir updated to swpm_sapinst_path instead of sap_swpm_sapcar_path. This way we can override sapinst_path value and extract SWPM to dedicated folder
    chdir: "{{ sap_swpm_sapinst_path }}"
  changed_when: "'SAPCAR: processing archive' in sap_swpm_extractswpm.stdout"
  # condition to be able to skip SWPM extraction, helpful when on NFS drive and running SWPM against several hosts in parallel
  when: sap_swpm_sapinst_extract != 'false' or sap_swpm_sapinst_extract is undefined
